# Project: C0001
# Makefile created by Dev-C++ 6.7.5

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"d:/softwarefiles/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/" -L"d:/softwarefiles/dev-cpp/mingw32/lib/gcc/" -L"d:/softwarefiles/dev-cpp/mingw32/mingw32/lib/" -L"d:/softwarefiles/dev-cpp/mingw32/lib/" -L"D:/SoftwareFiles/Dev-Cpp/MinGW32/lib" -L"D:/SoftwareFiles/Dev-Cpp/MinGW32/mingw32/lib" -g3 -static
INCS     = -I"d:/softwarefiles/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include" -I"d:/softwarefiles/dev-cpp/mingw32/include" -I"d:/softwarefiles/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include-fixed"
CXXINCS  = -I"d:/softwarefiles/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++" -I"d:/softwarefiles/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++/mingw32" -I"d:/softwarefiles/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++/backward" -I"d:/softwarefiles/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include" -I"d:/softwarefiles/dev-cpp/mingw32/include" -I"d:/softwarefiles/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include-fixed"
BIN      = C0001.exe
CXXFLAGS = $(CXXINCS) -Wall -Wextra -g3
ENCODINGS = -finput-charset=utf-8 -fexec-charset=gbk
CFLAGS   = $(INCS) -Wall -Wextra -g3
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "$(BIN)" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS) 
